/**
 * MEMORY.md — the persistent-memory slot, rendered from the JSONL state.
 *
 * This file is generated, never hand-edited. The reason it exists as a file at
 * all, rather than living only inside the prompt, is that the learner should be
 * able to open it and see exactly what the system believes about them: which
 * nodes are established, what is decaying, which wrong models are still
 * standing. A memory you cannot inspect is a memory you cannot correct.
 *
 * It is regenerated at session start and after every review, so it can never
 * drift from `learning/*.jsonl`, which remains the source of truth.
 */

import * as fs from "node:fs";
import * as path from "node:path";

import { misconceptionOpen, queue } from "./priority.ts";
import { topicStats } from "./report.ts";
import type { Store } from "./store.ts";

export const MEMORY_FILE = "MEMORY.md";

const HEADER = `<!-- Generated by the roots memory extension. Do not edit by hand.
     Source of truth is learning/*.jsonl. -->`;

export function renderDigest(store: Store, now: Date = new Date()): string {
	const cards = store.readCards();
	const nodes = store.readGraph();
	const parts: string[] = [`# Memory`, HEADER];

	if (cards.length === 0 && nodes.length === 0) {
		parts.push(
			"\nNothing established yet. This is the first session, or nothing has been " +
				"taught with the `teach` skill.",
		);
		return `${parts.join("\n")}\n`;
	}

	// ─── the graph: what is already standing ─────────────────────────────────
	if (nodes.length > 0) {
		parts.push("\n## Established");
		parts.push(
			"Nodes already taught and confirmed. Build on these rather than restating them.\n",
		);
		const byTopic = new Map<string, typeof nodes>();
		for (const n of nodes) {
			byTopic.set(n.topic, [...(byTopic.get(n.topic) ?? []), n]);
		}
		for (const [topic, list] of [...byTopic].sort()) {
			parts.push(`**${topic}**`);
			// Roots first, then derived — it reads as the build order.
			const ordered = [...list].sort((a, b) =>
				a.kind === b.kind ? a.id.localeCompare(b.id) : a.kind === "root" ? -1 : 1,
			);
			for (const n of ordered) {
				const deps = n.dependsOn.length ? ` ← ${n.dependsOn.join(", ")}` : "";
				parts.push(`- \`${n.id}\` (${n.kind}) ${n.label}${deps}`);
			}
			parts.push("");
		}
	}

	// ─── what is decaying ────────────────────────────────────────────────────
	const due = queue(cards, now, { limit: 6 });
	const total = queue(cards, now).length;
	parts.push("\n## Due");
	if (total === 0) {
		parts.push(`Nothing due. ${cards.length} card(s) scheduled.`);
	} else {
		parts.push(
			`${total} of ${cards.length} card(s) due, hardest first:\n`,
		);
		for (const c of due) {
			const where = c.node ? `${c.topic} › ${c.node}` : c.topic;
			parts.push(`- [${c.id}] ${where} — ${c.reason}`);
		}
		if (total > due.length) parts.push(`- …and ${total - due.length} more`);
	}

	// ─── wrong models still in place ─────────────────────────────────────────
	const open = cards.filter((c) => c.misconception && misconceptionOpen(c));
	if (open.length > 0) {
		parts.push("\n## Open misconceptions");
		parts.push(
			"Wrong models the learner has held and not yet clearly dropped. Anything " +
				"downstream of these is suspect.\n",
		);
		for (const c of open) parts.push(`- **${c.topic}** — ${c.misconception}`);
	}

	// ─── where they are weakest ──────────────────────────────────────────────
	const stats = topicStats(cards, now).filter((s) => s.correct + s.missed > 0);
	if (stats.length > 0) {
		parts.push("\n## Accuracy by topic");
		parts.push("Weakest first.\n");
		for (const s of stats) {
			const pct = Math.round(100 * s.accuracy);
			parts.push(
				`- **${s.topic}** — ${pct}% over ${s.correct + s.missed} answers, ${s.cards} card(s)`,
			);
		}
	}

	return `${parts.join("\n")}\n`;
}

/** Write MEMORY.md to the project root. Returns its contents. */
export function writeDigest(store: Store, cwd: string, now: Date = new Date()): string {
	const body = renderDigest(store, now);
	try {
		fs.writeFileSync(path.join(cwd, MEMORY_FILE), body, "utf8");
	} catch {
		// The prompt slot still works from the returned string even if the write
		// fails (read-only checkout, missing permissions). Never block on it.
	}
	return body;
}
