/**
 * MEMORY.md — the persistent-memory slot, rendered from the JSONL state.
 *
 * This file is generated, never hand-edited. The reason it exists as a file at
 * all, rather than living only inside the prompt, is that the learner should be
 * able to open it and see exactly what the system believes about them: which
 * nodes are established, what is decaying, which wrong models are still
 * standing. A memory you cannot inspect is a memory you cannot correct.
 *
 * It is regenerated at session start and after every review, so it can never
 * drift from `learning/*.jsonl`, which remains the source of truth.
 */

import * as fs from "node:fs";
import * as path from "node:path";

import { misconceptionOpen, queue } from "./priority.ts";
import { topicStats } from "./report.ts";
import type { Card, Node, Store } from "./store.ts";

export const MEMORY_FILE = "MEMORY.md";

const HEADER = `<!-- Generated by the roots memory extension. Do not edit by hand.
     Source of truth is learning/*.jsonl. -->`;

const EMPTY =
	"\nNothing established yet. This is the first session, or nothing has been " +
	"taught with the `teach` skill.";

function groupByTopic(nodes: Node[]): Array<[string, Node[]]> {
	const byTopic = new Map<string, Node[]>();
	for (const n of nodes) byTopic.set(n.topic, [...(byTopic.get(n.topic) ?? []), n]);
	return [...byTopic].sort(([a], [b]) => a.localeCompare(b));
}

/** Roots before derived, so a topic reads in the order it was built. */
const buildOrder = (a: Node, b: Node) =>
	a.kind === b.kind ? a.id.localeCompare(b.id) : a.kind === "root" ? -1 : 1;

function established(nodes: Node[]): string[] {
	if (nodes.length === 0) return [];
	const out = [
		"\n## Established",
		"Nodes already taught and confirmed. Build on these rather than restating them.\n",
	];
	for (const [topic, list] of groupByTopic(nodes)) {
		out.push(`**${topic}**`);
		for (const n of [...list].sort(buildOrder)) {
			const deps = n.dependsOn.length ? ` ← ${n.dependsOn.join(", ")}` : "";
			out.push(`- \`${n.id}\` (${n.kind}) ${n.label}${deps}`);
		}
		out.push("");
	}
	return out;
}

function decaying(cards: Card[], now: Date): string[] {
	const total = queue(cards, now).length;
	if (total === 0) {
		return ["\n## Due", `Nothing due. ${cards.length} card(s) scheduled.`];
	}

	const top = queue(cards, now, { limit: 6 });
	const out = ["\n## Due", `${total} of ${cards.length} card(s) due, hardest first:\n`];
	for (const c of top) {
		const where = c.node ? `${c.topic} › ${c.node}` : c.topic;
		out.push(`- [${c.id}] ${where} — ${c.reason}`);
	}
	if (total > top.length) out.push(`- …and ${total - top.length} more`);
	return out;
}

function stillWrong(cards: Card[]): string[] {
	const open = cards.filter((c) => c.misconception && misconceptionOpen(c));
	if (open.length === 0) return [];
	return [
		"\n## Open misconceptions",
		"Wrong models the learner has held and not yet clearly dropped. Anything " +
			"downstream of these is suspect.\n",
		...open.map((c) => `- **${c.topic}** — ${c.misconception}`),
	];
}

function accuracy(cards: Card[], now: Date): string[] {
	const stats = topicStats(cards, now).filter((s) => s.correct + s.missed > 0);
	if (stats.length === 0) return [];
	return [
		"\n## Accuracy by topic",
		"Weakest first.\n",
		...stats.map((s) => {
			const pct = Math.round(100 * s.accuracy);
			const answers = s.correct + s.missed;
			return `- **${s.topic}** — ${pct}% over ${answers} answers, ${s.cards} card(s)`;
		}),
	];
}

export function renderDigest(store: Store, now: Date = new Date()): string {
	const cards = store.readCards();
	const nodes = store.readGraph();

	const body =
		cards.length === 0 && nodes.length === 0
			? [EMPTY]
			: [
					...established(nodes),
					...decaying(cards, now),
					...stillWrong(cards),
					...accuracy(cards, now),
				];

	return `${["# Memory", HEADER, ...body].join("\n")}\n`;
}

/** Write MEMORY.md to the project root. Returns its contents. */
export function writeDigest(store: Store, cwd: string, now: Date = new Date()): string {
	const body = renderDigest(store, now);
	try {
		fs.writeFileSync(path.join(cwd, MEMORY_FILE), body, "utf8");
	} catch {
		// The prompt slot still works from the returned string even if the write
		// fails (read-only checkout, missing permissions). Never block on it.
	}
	return body;
}
